"""Phase 5.1 Outcome B: qualitative XRD phase summary and XPS corroboration.

This script is used when Rietveld refinement does not converge (Outcome B from
05.1-03). It produces a qualitative phase assignment table and a scoped thesis
claim text file, without relying on converged weight fractions.

The hard-block gate in post_process.py prevents Phase 6 from running on
non-converged output. This script provides an alternative scoped output path.

Usage:
    /opt/homebrew/bin/python3.14 xrd_qualitative_summary.py
"""

from __future__ import annotations

import json
from pathlib import Path

import pandas as pd


_XRD_ROOT = Path(__file__).resolve().parent
RESULTS_DIR = _XRD_ROOT / "results"
DIAGNOSTICS_JSON = RESULTS_DIR / "phase5_stage_diagnostics.json"
QUAL_TABLE_CSV = RESULTS_DIR / "xrd_phase_qualitative.csv"
QUAL_TABLE_TEX = RESULTS_DIR / "xrd_phase_qualitative.tex"
SCOPED_CLAIM_TXT = RESULTS_DIR / "xrd_scoped_thesis_claim.txt"


# Qualitative phase assignments per 05.1-RESEARCH.md method decision
# weight_fraction: not available (non-converged) — replaced by qualitative presence
PHASE_ASSIGNMENTS = [
    {
        "xrd_phase": "TaRe",
        "xps_species": "Ta alloy / Re metal",
        "xps_element": "Ta4f / Re4f",
        "presence": "confirmed (expected — BCC metal film)",
        "lattice_parameter_a_Ang": 3.19,
        "lattice_parameter_note": "initial model value; not refined (non-converged)",
        "weight_fraction_note": "not quantifiable — film texture prevents powder Rietveld",
    },
    {
        "xrd_phase": "Al2O3",
        "xps_species": "N/A (substrate)",
        "xps_element": "",
        "presence": "confirmed (dominant — thick crystalline substrate)",
        "lattice_parameter_a_Ang": 5.178,
        "lattice_parameter_note": "initial model value; not refined (non-converged)",
        "weight_fraction_note": "dominates diffractogram; no quantification attempted",
    },
    {
        "xrd_phase": "Ta2O5",
        "xps_species": "Ta+5 (Ta2O5)",
        "xps_element": "Ta4f",
        "presence": "not resolved — oxide expected amorphous (per McLellan et al.)",
        "lattice_parameter_a_Ang": float("nan"),
        "lattice_parameter_note": "not modeled in diagnostic run",
        "weight_fraction_note": "indeterminate — amorphous fraction invisible to Bragg diffraction",
    },
    {
        "xrd_phase": "ReO2",
        "xps_species": "ReO2 (Re4+)",
        "xps_element": "Re4f",
        "presence": "deprioritized — Re oxide suppressed (per Re-on-sapphire TEM/EDS)",
        "lattice_parameter_a_Ang": float("nan"),
        "lattice_parameter_note": "excluded from model",
        "weight_fraction_note": "not quantified — inadmissible as primary phase",
    },
]

SCOPED_CLAIM_TEXT = """\
XRD Scoped Thesis Claim (Outcome B — amorphous-dominated specimen)
==================================================================

Generated by: xrd_qualitative_summary.py
Context: Plan 05.1-03 refinement did not converge (Rwp = 90.0%, SVD
singularity at Stage 2 for both 3-phase and 2-phase models).
Diagnosis: specimen limitation — (111)-textured thin-film + substantially
amorphous oxide layer cannot be modeled as random-powder Rietveld.

---

Scoped XRD chapter claim (defensible):

"XRD confirms the crystalline phases present in the oxidized TaRe film.
The dominant diffraction signal arises from the Al2O3 sapphire substrate
and the textured TaRe bcc metal film. The oxide phase is expected to be
substantially amorphous based on analogous Ta-on-sapphire measurements
[McLellan et al.]; XRD cannot quantify amorphous fractions. The absence
of resolved Ta2O5 crystalline reflections above background is consistent
with the predominantly amorphous native oxide assignment. The TaRe bcc
lattice parameter a ≈ 3.19 Å (initial model; not refined due to
non-convergence) is consistent with published values for TaRe bcc alloys
and corroborates the Ta alloy and Re metal assignments in XPS Ta4f and Re4f."

---

What XRD can defensibly claim for this specimen:
1. Phase presence/absence: TaRe bcc (confirmed), Al2O3 (confirmed),
   crystalline Ta2O5 (not resolved — consistent with amorphous oxide model)
2. TaRe lattice parameter: constrained by bcc {110}/{200}/{211} positions
   (could be refined with converged refinement; not quantified here)
3. XPS corroboration: crystalline phase assignments consistent with XPS
   Ta5+ (oxide) and Ta alloy / Re metal (metal) assignments

What XRD cannot claim:
- Absolute weight fractions of oxide phases (non-converged refinement)
- Absence of amorphous oxide (amorphous invisible to Bragg diffraction)
- Rhenium oxide quantification (suppressed per TEM/EDS evidence)

---

Phase 6 scope under Outcome B:
- Pattern-only plot: results/TaRe_xrd_pattern_diagnostic.png
  (diagnostic figure; Rwp = 90.0% printed as WARNING — not thesis-ready)
- Qualitative XRD/XPS table: results/xrd_phase_qualitative.csv / .tex
  (phase presence assignments, no weight fractions)
- No thesis-facing weight fraction table (hard-blocked by post_process.py)
"""


def main() -> None:
    RESULTS_DIR.mkdir(parents=True, exist_ok=True)

    # Load diagnostics for provenance
    diag_info = {}
    if DIAGNOSTICS_JSON.exists():
        with DIAGNOSTICS_JSON.open(encoding="utf-8") as f:
            diag_info = json.load(f)

    rwp_history = diag_info.get("rwp_history", [])
    failure = diag_info.get("failure", {})

    print("XRD Outcome B: qualitative phase summary")
    print(f"  Rwp history: {[f'{r:.2f}%' for r in rwp_history]}")
    print(f"  Failure: Stage {failure.get('stage', '?')} — {failure.get('reason', 'unknown')}")
    print()

    # Build qualitative table
    df = pd.DataFrame(PHASE_ASSIGNMENTS)
    df.to_csv(QUAL_TABLE_CSV, index=False)
    print(f"Qualitative table saved → {QUAL_TABLE_CSV}")

    # LaTeX table (presence assignments only — no weight fractions)
    latex_cols = ["xrd_phase", "xps_species", "xps_element", "presence"]
    latex_df = df[latex_cols].copy()
    latex_str = latex_df.to_latex(
        index=False,
        na_rep="—",
        caption=(
            "Qualitative XRD phase assignments for the oxidized TaRe/sapphire specimen. "
            "Weight fractions are not reported: Rietveld refinement did not converge "
            "(Rwp = 90\\%{}) due to thin-film texture and amorphous oxide fraction."
        ),
        label="tab:xrd_qualitative",
        column_format="llll",
    )
    QUAL_TABLE_TEX.write_text(latex_str, encoding="utf-8")
    print(f"LaTeX table saved → {QUAL_TABLE_TEX}")

    # Scoped claim text
    SCOPED_CLAIM_TXT.write_text(SCOPED_CLAIM_TEXT, encoding="utf-8")
    print(f"Scoped claim text saved → {SCOPED_CLAIM_TXT}")

    print()
    print("Phase 6 Outcome B scope:")
    print("  - Pattern-only diagnostic figure (results/TaRe_xrd_pattern_diagnostic.png)")
    print("  - Qualitative XRD/XPS table (no weight fractions)")
    print("  - Hard-block gate for weight-fraction table: ACTIVE")


if __name__ == "__main__":
    main()
